# Generated by Django 2.2.28 on 2023-01-30 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMEmployeesCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('registration', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('effective_role', models.CharField(blank=True, max_length=100, null=True)),
                ('comission_role', models.CharField(blank=True, max_length=100, null=True)),
                ('ordinance_number_nomination', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('ordinance_year_nomination', models.CharField(blank=True, max_length=4, verbose_name='Ano')),
                ('ordinance_number_retirement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('ordinance_year_retirement', models.CharField(blank=True, max_length=4, verbose_name='Ano')),
                ('workplace', models.CharField(max_length=100)),
                ('stability', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
